# ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]

# Use the official Maven image as the base image
FROM maven:3.8.5-openjdk-17 AS build

# Set the working directory
WORKDIR /app

# Copy the pom.xml and any other necessary configuration files
COPY ./src /app/src
COPY ./pom.xml /app
COPY target/*.jar app.jar

# Build the application
# RUN mvn clean package -Dmaven.test.skip=true
RUN mvn clean package

# Create a new image for running the application
FROM openjdk:17-jdk-slim

# Set the working directory
# WORKDIR /app

# Copy the built JAR file from the previous stage
COPY --from=build /app/target/*.jar app.jar

# Expose the port on which the Spring Boot application will run
EXPOSE 8080

# Command to run the application
CMD ["java", "-Dspring.profiles.active=production","-jar", "app.jar"]
