spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855